### ISSUE TITLE
SSH WS WITH PORT 443&80 NOT WORKING

### ISSUE THREAD

**Issue by sshwsvpn** [Manssizz/scriptvps#3]
SSH WS WITH PORTS 443&80 DOES NOT WORK
SSH WS OVPN DOES NOT WORK
SSH OVPN WITH SSL DOES NOT WORK

NYCE SCRIPT, SHARE A DONATOR LINK, WILL SEND SOME GIFT FOR U.

OTHER FT LIKE VLESS, AND VMESS WORK

TESTED ON VPS DIGITALOCEAN & AWS

**Comment by Manssizz** [comment]
last commit missing ssh db. you can try again and give me feedback.

**Comment by sshwsvpn** [comment]
One more bug, After installing this script, I cannot access my VPS, Access denied
cannot access VPS login with a password but it ok when using the ssh key

SSH Websocket Get Bad Request 400 port 443&80 [same]

and

caddy. services error Failed To start
<pre><code>Job for caddy.service failed because the control process exited with error code.
See "systemctl status caddy.service" and "journalctl -xe" for details.</pre></code>

**Comment by Manssizz** [comment]
- caddy was optional in latest update .
- ssh using port 83 (i didn't update yet)
- ovpn for tls using port 1194.
both of them i can't test. because i only using trojan,vless and vmess

**Comment by Manssizz** [comment]
fixed on latest version
