### ISSUE TITLE
XRAY GA SUPORT MULTIPATH JADI GA SUPORT OPOK BANG :(

### ISSUE THREAD

**Issue by Sonzai-X** [Manssizz/scriptvps#4]
Xray core XTLS ga bisa opok bang 
Kebanyakan yang yg suport buat opok core dari dharak36 klo gasalah

**Comment by Manssizz** [comment]
coba pakai vmess
![image](https://user-images.githubusercontent.com/23637327/216774836-c1012d39-f6bd-4840-98ab-662dfa034d5b.png)

**Comment by sonzaiekkusu** [comment]
> coba pakai vmess ![image](https://user-images.githubusercontent.com/23637327/216774836-c1012d39-f6bd-4840-98ab-662dfa034d5b.png)

itu opok kah bang??

**Comment by Sonzai-X** [comment]
> coba pakai vmess ![image](https://user-images.githubusercontent.com/23637327/216774836-c1012d39-f6bd-4840-98ab-662dfa034d5b.png)


![Screenshot_2023-02-05-15-55-38-244_com gatcha ang](https://user-images.githubusercontent.com/124268173/216810236-b46fda7c-ccf5-44b2-af34-70ad5da04a20.jpg)
Gakonek ttp bang

**Comment by Sonzai-X** [comment]
> coba pakai vmess ![image](https://user-images.githubusercontent.com/23637327/216774836-c1012d39-f6bd-4840-98ab-662dfa034d5b.png)

![Uploading Screenshot_2023-02-05-15-58-37-732_com.gatcha.ang.jpg…]()
Tetep bamg ga konek udah di update juga

**Comment by Sonzai-X** [comment]
> coba pakai vmess ![image](https://user-images.githubusercontent.com/23637327/216774836-c1012d39-f6bd-4840-98ab-662dfa034d5b.png)

![Screenshot_2023-02-05-15-58-37-732_com gatcha ang](https://user-images.githubusercontent.com/124268173/216810325-7798204c-72cc-4106-bc73-6761d4c276a7.jpg)
Tetep ga konek bang
