### ISSUE TITLE
Stuck at ssl

### ISSUE THREAD

**Issue by Rroonnin** [Manssizz/scriptvps#7]
Bang,, scriptnya stuck setelah sertifikat ssl berhasil dipasang. ada solusi?
![image](https://user-images.githubusercontent.com/86831620/228127734-fda70106-28a6-4320-b9c7-938b60af027b.png)

**Comment by Manssizz** [comment]
osnya apa?

**Comment by Manssizz** [comment]
osnya apa?

**Comment by Rroonnin** [comment]
Ubuntu 20 sama 22

**Comment by Manssizz** [comment]
stucknya begini?
![image](https://user-images.githubusercontent.com/23637327/229242915-c3dcba19-bf38-4460-a7b0-c4b700cb0ee1.png)
