### ISSUE TITLE
Delete pre-created users

### ISSUE THREAD

**Issue by essoojay** [Manssizz/scriptvps#9]
thank you for your efforts BUT

You still need to delete pre-created users. Let users create their own

Xray are all offline, probably port mapping issue

i see that extra ssh port 39 and 339 are removed and extra ssh_key auth kind of suppressed

My point is why create those backdoors into the script.?

thanks again

**Comment by Manssizz** [comment]
first, user was deleted after your report

second, xray service work perfect and i use by myself.
![image](https://github.com/Manssizz/scriptvps/assets/23637327/6b51da87-23f7-48cf-96e6-ad798950da91)

third, why use port 39 for ssh? look at below. i was revert ssh login to 22 on this script. but i prefer still use custom port.
![image](https://github.com/Manssizz/scriptvps/assets/23637327/f9b0a18f-3c1e-4ce3-a8e7-a8c0277d24d0)
